import type { NBTCompoundTag } from "../../packages/nbt/src/tags.js";

export default {
  overworld: {
    type: "compound",
    name: "",
    value: [
      { type: "byte", name: "has_skylight", value: 1 },
      { type: "byte", name: "has_ceiling", value: 0 },
      { type: "byte", name: "ultrawarm", value: 0 },
      { type: "byte", name: "natural", value: 1 },
      { type: "double", name: "coordinate_scale", value: 1 },
      { type: "byte", name: "bed_works", value: 1 },
      { type: "byte", name: "respawn_anchor_works", value: 0 },
      { type: "int", name: "min_y", value: -64 },
      { type: "int", name: "height", value: 384 },
      { type: "int", name: "logical_height", value: 384 },
      {
        type: "string",
        name: "infiniburn",
        value: "#minecraft:infiniburn_overworld",
      },
      { type: "string", name: "effects", value: "minecraft:overworld" },
      { type: "float", name: "ambient_light", value: 0 },
      { type: "byte", name: "piglin_safe", value: 0 },
      { type: "byte", name: "has_raids", value: 1 },
      {
        type: "compound",
        name: "monster_spawn_light_level",
        value: [
          { type: "string", name: "type", value: "minecraft:uniform" },
          { type: "int", name: "min_inclusive", value: 0 },
          { type: "int", name: "max_inclusive", value: 7 },
        ],
      },
      { type: "int", name: "monster_spawn_block_light_limit", value: 0 },
    ],
  },
  overworld_caves: {
    type: "compound",
    name: "",
    value: [
      { type: "byte", name: "has_skylight", value: 1 },
      { type: "byte", name: "has_ceiling", value: 1 },
      { type: "byte", name: "ultrawarm", value: 0 },
      { type: "byte", name: "natural", value: 1 },
      { type: "double", name: "coordinate_scale", value: 1 },
      { type: "byte", name: "bed_works", value: 1 },
      { type: "byte", name: "respawn_anchor_works", value: 0 },
      { type: "int", name: "min_y", value: -64 },
      { type: "int", name: "height", value: 384 },
      { type: "int", name: "logical_height", value: 384 },
      {
        type: "string",
        name: "infiniburn",
        value: "#minecraft:infiniburn_overworld",
      },
      { type: "string", name: "effects", value: "minecraft:overworld" },
      { type: "float", name: "ambient_light", value: 0 },
      { type: "byte", name: "piglin_safe", value: 0 },
      { type: "byte", name: "has_raids", value: 1 },
      {
        type: "compound",
        name: "monster_spawn_light_level",
        value: [
          { type: "string", name: "type", value: "minecraft:uniform" },
          { type: "int", name: "min_inclusive", value: 0 },
          { type: "int", name: "max_inclusive", value: 7 },
        ],
      },
      { type: "int", name: "monster_spawn_block_light_limit", value: 0 },
    ],
  },
  the_end: {
    type: "compound",
    name: "",
    value: [
      { type: "byte", name: "has_skylight", value: 0 },
      { type: "byte", name: "has_ceiling", value: 0 },
      { type: "byte", name: "ultrawarm", value: 0 },
      { type: "byte", name: "natural", value: 0 },
      { type: "double", name: "coordinate_scale", value: 1 },
      { type: "byte", name: "bed_works", value: 0 },
      { type: "byte", name: "respawn_anchor_works", value: 0 },
      { type: "int", name: "min_y", value: 0 },
      { type: "int", name: "height", value: 256 },
      { type: "int", name: "logical_height", value: 256 },
      {
        type: "string",
        name: "infiniburn",
        value: "#minecraft:infiniburn_end",
      },
      { type: "string", name: "effects", value: "minecraft:the_end" },
      { type: "float", name: "ambient_light", value: 0 },
      { type: "byte", name: "piglin_safe", value: 0 },
      { type: "byte", name: "has_raids", value: 1 },
      {
        type: "compound",
        name: "monster_spawn_light_level",
        value: [
          { type: "string", name: "type", value: "minecraft:uniform" },
          { type: "int", name: "min_inclusive", value: 0 },
          { type: "int", name: "max_inclusive", value: 7 },
        ],
      },
      { type: "int", name: "monster_spawn_block_light_limit", value: 0 },
      { type: "long", name: "fixed_time", value: 6000n },
    ],
  },
  the_nether: {
    type: "compound",
    name: "",
    value: [
      { type: "byte", name: "has_skylight", value: 0 },
      { type: "byte", name: "has_ceiling", value: 1 },
      { type: "byte", name: "ultrawarm", value: 1 },
      { type: "byte", name: "natural", value: 0 },
      { type: "double", name: "coordinate_scale", value: 8 },
      { type: "byte", name: "bed_works", value: 0 },
      { type: "byte", name: "respawn_anchor_works", value: 1 },
      { type: "int", name: "min_y", value: 0 },
      { type: "int", name: "height", value: 256 },
      { type: "int", name: "logical_height", value: 128 },
      {
        type: "string",
        name: "infiniburn",
        value: "#minecraft:infiniburn_nether",
      },
      { type: "string", name: "effects", value: "minecraft:the_nether" },
      { type: "float", name: "ambient_light", value: 0.1 },
      { type: "byte", name: "piglin_safe", value: 1 },
      { type: "byte", name: "has_raids", value: 0 },
      { type: "int", name: "monster_spawn_block_light_limit", value: 15 },
      { type: "int", name: "monster_spawn_light_level", value: 7 },
      { type: "long", name: "fixed_time", value: 18000n },
    ],
  },
} as Record<string, NBTCompoundTag>;
